version: "3"

services:
    
  # potgresql for data persist
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes: 
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql

  consumer:
    build: 
      context: ./kafka
      dockerfile: Dockerfile.consumer
    command: ["./wait-for-it.sh", "db:5432", "--timeout=30", "--", "./consumer"]
    depends_on: 
      - db
      - kafka

  rest_api:
    build: 
      context: ./rest_api
    ports:
      - "8080:8080"
    
  ui:
    build: 
      context: ./ui
    ports:
      - "80:80"
  
  ws_server:
    build: 
      context: ./ws_server
    command: ["./wait-for-it.sh", "db:5432", "--timeout=30", "--", "node", "index.js"]
    ports:
      - "3000:3000"
    depends_on: 
      - db

  # bitnami kafka dependends
  zookeeper:
    image: "docker.io/bitnami/zookeeper:3-debian-10"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "docker.io/bitnami/kafka:2-debian-10"
    ports:
      - "9092:9092"
    expose: 
      - "9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
